name: export-lua53
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y lua5.3
      - run: |
          mkdir compiler
          cp /usr/bin/lua5.3 /usr/bin/luac5.3 compiler/
          ldd /usr/bin/luac5.3
          cp /lib/x86_64-linux-gnu/liblua5.3.so.0 compiler/ || true
          cp /lib/x86_64-linux-gnu/libreadline.so.8 compiler/ || true
          cp /lib/x86_64-linux-gnu/libtinfo.so.6 compiler/ || true
      - uses: actions/upload-artifact@v4
        with:
          name: lua53-compiler
          path: compiler/
