name: build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y lua5.3 nodejs
      - run: luac5.3 -s -o a17t_raw.luac a17t.lua
      - run: node normalize_luac53_mt12.js a17t_raw.luac a17t.luac
      - uses: actions/upload-artifact@v4
        with:
          name: a17t
          path: |
            a17t.lua
            a17t_raw.luac
            a17t.luac
